---
- name: install postgresql
  pkgng:
    name:
      - postgresql{{ pg_version | regex_replace("[^0-9]","") }}-server
      - postgresql{{ pg_version | regex_replace("[^0-9]","") }}-pltcl
      - postgresql{{ pg_version | regex_replace("[^0-9]","") }}-contrib
      - 'py{{ ansible_python.version.major }}{{ ansible_python.version.minor }}-pip'
    state: present
  register: install_pg

- name: install psycopg2 python module
  pip:
    executable: 'pip-{{ ansible_python.version.major }}.{{ ansible_python.version.minor }}'
    name: psycopg2
    state: present
 
- name: login.conf
  blockinfile:
    dest: /etc/login.conf
    marker: '# {mark} criecm.postgresql'
    block: |
      {{ pg_class }}:\
        :lang={{ pg_lc }}:\
        :setenv=LC_MESSAGES={{ pg_lc_messages | default(pg_lc) }}:\
        :setenv=LC_ALL={{ pg_lc }}:\
        :setenv=LC_COLLATE={{ pg_lc }}:\
        :charset=UTF-8:\
        :tc=daemon:

  when: pg_class | default(False)
  register: loginconf
  notify: cap_mkdb login.conf

- name: cap_mkdb
  command: '/usr/bin/cap_mkdb /etc/login.conf'
  when: loginconf.changed

- name: postgres user
  user:
    group: '{{ pg_group }}'
    name: '{{ pg_owner }}'
    shell: /usr/local/bin/zsh
    login_class: '{{ pg_class | default(omit) }}'
    home: '{{ pg_owner_home }}'

- name: zfs
  zfs:
    name: '{{ pg_zfs_base }}/{{ pg_datasubdir }}'
    state: present
    extra_zfs_properties:
      mountpoint: '{{ pg_basedir }}/{{ pg_datasubdir }}'
      recordsize: 8K
  when: pg_zfs_base != ""

- name: rc.conf
  lineinfile:
    dest: /etc/rc.conf
    line: '{{ item.key }}="{{ item.value }}"'
    regexp: '^{{ item.key }}='
  with_items:
    - { key: postgresql_enable, value: "YES" }
    - { key: postgresql_dbdir, value: '{{ pg_basedir }}/{{ pg_datasubdir }}' }
    - { key: postgresql_class, value: '{{ pg_class }}' }
  notify: restart postgresql

- name: syslog dirs
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - /usr/local/etc/syslog.d
    - /usr/local/etc/newsyslog.conf.d
  when: pg_logdest == "syslog"

- name: syslog postgresql
  copy:
    dest: /usr/local/etc/syslog.d/postgresql.conf
    content: |
      {{ pg_syslog_facility }}.*   /var/log/postgresql.log
  when: pg_logdest == "syslog"

- name: newsyslog
  copy:
    force: no
    dest: /usr/local/etc/newsyslog.conf.d/postgresql.conf
    content: |
      /var/log/postgresql.log  root:{{ pg_group }}  640 7 1000  @T00  X
  when: pg_logdest == "syslog"
