---
- name: get postgresql infos
  postgresql_info:
  become: True
  become_user: '{{ pg_owner }}'
  become_method: su
  register: pg_actual

- name: 'pg user {{ pg_user.name }}'
  postgresql_user:
    name: '{{ pg_user.name }}'
    priv: '{{ pg_user.priv | default(omit) }}'
    role_attr_flags: '{{ pg_user.role_attr_flags | default(omit) }}'
    password: '{{ pg_user.password | default(pg_user.name+pg_random | hash("sha256")) }}'
    state: present
  become: True
  become_user: '{{ pg_owner }}'
  become_method: su

- name: 'create db {{ pg_user.name }}'
  postgresql_db:
    name: '{{ pg_user.db }}'
    owner: '{{ pg_user.name }}'
    state: present
  become: True
  become_user: '{{ pg_owner }}'
  become_method: su
  when: '"db" in pg_user.keys() and not pg_user.db in pg_actual.databases.keys() and not pg_user.db in pg_dbs | map(attribute="name") and not pg_user.db == "all"'

- name: access in pg_hba.conf for {{ pg_user.name }}
  blockinfile:
    path: '{{ pg_basedir }}/{{ pg_datasubdir }}/pg_hba.conf'
    mode: '0640'
    group: '{{ pg_group }}'
    marker: '# {mark} Ansible block for user {{ pg_user.name }}'
    block: |
      {% for host in pg_user.hosts | default(['all']) %}
      host	{{ pg_user.db | default(pg_user.name) }}	{{ pg_user.name }}	{{ host }}	{% if pg_user.password | default(False) %}md5{% else %}trust{% endif %}
      
      {% endfor %}
  notify: reload postgresql
